# Generated by Django 6.0.8 on 2026-08-10 00:19

import apps.accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico')),
                ('nombre', models.CharField(blank=True, max_length=150, verbose_name='nombre completo')),
                ('cargo', models.CharField(blank=True, max_length=150, verbose_name='cargo o dependencia')),
                ('rol', models.CharField(choices=[('superadmin', 'Superadministrador'), ('usuario', 'Usuario de consulta')], default='usuario', max_length=20, verbose_name='rol')),
                ('is_active', models.BooleanField(default=True, help_text='Si se desactiva, el enlace mágico deja de funcionar para esta persona.', verbose_name='acceso habilitado')),
                ('is_staff', models.BooleanField(default=False, verbose_name='puede entrar al admin de Django')),
                ('supabase_uid', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='UID de Supabase')),
                ('notas', models.TextField(blank=True, verbose_name='notas internas')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de alta')),
                ('ultimo_ingreso', models.DateTimeField(blank=True, null=True, verbose_name='último ingreso')),
                ('total_ingresos', models.PositiveIntegerField(default=0, verbose_name='ingresos')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('invitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitaciones', to=settings.AUTH_USER_MODEL, verbose_name='invitado por')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['nombre', 'correo'],
            },
            managers=[
                ('objects', apps.accounts.models.GestorUsuarios()),
            ],
        ),
        migrations.CreateModel(
            name='EnlaceMagico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
                ('usado_en', models.DateTimeField(blank=True, null=True)),
                ('ip_solicitud', models.GenericIPAddressField(blank=True, null=True)),
                ('agente', models.CharField(blank=True, max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlaces', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'enlace mágico',
                'verbose_name_plural': 'enlaces mágicos',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['usuario', '-creado_en'], name='accounts_en_usuario_e9ad69_idx')],
            },
        ),
    ]
