# Generated by Django 6.0.8 on 2026-08-10 00:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True, verbose_name='identificador')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='descripción')),
                ('color', models.CharField(default='#6B9A38', help_text='Color hexadecimal usado en la etiqueta de la galería.', max_length=7, verbose_name='color de la etiqueta')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Fotografia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=180, verbose_name='título')),
                ('slug', models.SlugField(blank=True, max_length=200, verbose_name='identificador')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('anio', models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='año')),
                ('imagen', models.BinaryField(verbose_name='imagen')),
                ('imagen_mime', models.CharField(default='image/jpeg', max_length=40)),
                ('imagen_peso', models.PositiveIntegerField(default=0, verbose_name='peso en bytes')),
                ('ancho', models.PositiveIntegerField(default=0)),
                ('alto', models.PositiveIntegerField(default=0)),
                ('miniatura', models.BinaryField(blank=True, null=True, verbose_name='miniatura')),
                ('miniatura_mime', models.CharField(default='image/jpeg', max_length=40)),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='SHA-256')),
                ('archivo_original', models.CharField(blank=True, max_length=255, verbose_name='archivo original')),
                ('publicada', models.BooleanField(db_index=True, default=True, verbose_name='publicada')),
                ('destacada', models.BooleanField(default=False, verbose_name='destacada')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizada')),
                ('indice_busqueda', models.TextField(blank=True, editable=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fotografias', to='gallery.categoria', verbose_name='categoría')),
                ('subida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotografias', to=settings.AUTH_USER_MODEL, verbose_name='subida por')),
            ],
            options={
                'verbose_name': 'fotografía',
                'verbose_name_plural': 'fotografías',
                'ordering': ['-anio', '-creado_en'],
                'indexes': [models.Index(fields=['-anio', '-creado_en'], name='gallery_fot_anio_bbf571_idx'), models.Index(fields=['categoria', '-anio'], name='gallery_fot_categor_7f0aa2_idx')],
            },
        ),
    ]
